services:
  database:
    image: 'postgres:15.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=dev'
      - 'POSTGRES_DB=carsharingdb'
      - 'POSTGRES_PASSWORD=dev123'
    

  app:
    image: jovan141/carsharingapp:latest  
    container_name: spring_app
    depends_on:
      - database
    ports:
      - "9100:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/carsharingdb
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      

